### ISSUE TITLE
Can't Preview, requires image file?

### ISSUE THREAD

**Issue by eleanorkonik** [deathau/cooklang-obsidian#1]
Per `Nothing is Lost` in Obsidian Discord, I can't see preview of my recipe because it looks like there's a bug currently that requires that you have an image file in the same directory as the `.cook` file that matches the `.cook` file name.

So if you have `myrecipe.cook` you need a `myrecipe.jpg` in the same directory.

**Comment by deathau** [comment]
Thanks for reporting this. Fixed in [0.0.3](https://github.com/deathau/cooklang-obsidian/releases/tag/0.0.3)
