### ISSUE TITLE
Support named timers

### ISSUE THREAD

**Issue by hmnd** [deathau/cooklang-obsidian#13]
Thanks for this awesome plugin!

The [CookLang spec](https://cooklang.org/docs/spec/#:~:text=timers%20can%20have%20a%20name%20too%3A) supports named timers, such as `~egg{3%minutes}`, but this syntax does not seem to work yet with the plugin.

**Comment by deathau** [comment]
I've split off my parsing code into a separate library, and updated that with support for the latest spec.
Named timers should work fine now, and furthermore, there's new options for listing timers
