### ISSUE TITLE
Cannot create new recipe

### ISSUE THREAD

**Issue by RichSteele** [deathau/cooklang-obsidian#3]
It's not apparent how to create a new recipe: I can't find an entry in the command center (searched for "food" and "recipe"), right-click on a folder doesn't have any entry. It's not clear if I can create a file with a .food extension within Obsidian, either: I resorted to creating .md file and then changing its extension in Windows explorer.

System: Windows 10, Obisidian 0.13.2

**Comment by deathau** [comment]
Agreed. It's not clear at all, and I never really added any options for creating new `.cook` files. I don't know why it never even occurred to me to do so 😅 
There is a command I added for changing `.md` to `.cook` within Obsidian as per a request, but I should _definitely_ add some options to _create_ a `.cook` file.
